### ISSUE TITLE
Sugestão: alterar funcionamento de seleção na tela principal

### ISSUE THREAD

**Issue by BryanCruz** [centralufabc/centralufabc#3]
Na tela principal temos 3 botões que permitem customizar quais serão os painéis visíveis (fretado, aulas e cardápio).

Na minha opinião isso é contra-intuitivo, e uma sugestão seria colocar algo como um "pinning" para facilitar a visualização. 

Por exemplo, se eu selecionar "fretado" quero que apareça instantaneamente o painel do fretado no topo da tela, sem eu precisar dar o scroll.

**Comment by guilhermeb4rreto** [comment]
Obrigado pela sugestão! 

Estivemos pensando nesta questão, e pretendemos reformular esta funcionalidade em breve. :)
